### ISSUE TITLE
Ignore Selectors Not Working with Postcss/Gulp/Gulp-sass

### ISSUE THREAD

**Issue by rfarine** [postcss/postcss-bem-linter#83] opened 2016-03-08 20:31 UTC
Hello! I am having some trouble setting up `postcss-bem-linter` with Gulp, PostCss, and Gulp-Sass. 

Here is my Gulp task:

```js
gulp.task('sass:dev', function () {
  var processors = [
    autoprefixer(),
    lost(),
    bemLinter({
      preset: 'bem',
      componentName: /[a-z]+/,
      utilitySelectors: /u-[a-z]+/,
      ignoreSelectors: [
        /\.row/,
        /\.col/,
        /\.oui.*/,
        /\.vex.*/,
        /\.pika.*/,
        /\.vbox.*/,
        /\.slick.*/,
        /.+[%]/,
      ]
    }),
    reporter({ clearMessages: true }),
  ];

  return gulp.src('app/assets/css/*.scss')
    .pipe(sourcemaps.init())
    .pipe(sass({
      includePaths: ['app/assets', 'node_modules'],
      outputStyle : 'nested',
      sourceComments: 'map',
    }))
    .pipe(postcss(processors))
    .pipe(sourcemaps.write())
    .pipe(gulp.dest('public/assets/css'));
});
```

Here's an example of a file that is causing failures:

```scss
@import '../../css/vendor/vex';
@import '../../css/vendor/vex-theme-plain';

/** @define modal */
$module: modal;

.#{$module} { ... }
```

I am getting the following errors related to the `vendor/vex` and `vendor/vex-theme-plugin` stylesheets (which have not been `@define`'d, so I do not see why these would be linted at all!)

```bash
app/assets/css/application.css
1487:7	⚠  Invalid component selector ".vex *" [postcss-bem-linter]
1487:15	⚠  Invalid component selector ".vex *:before" [postcss-bem-linter]
1487:30	⚠  Invalid component selector ".vex *:after" [postcss-bem-linter]
1629:5	⚠  Invalid component selector ".vex.vex-theme-plain .vex-dialog-form .vex-dialog-input textarea" [postcss-bem-linter]
1630:5	⚠  Invalid component selector ".vex.vex-theme-plain .vex-dialog-form .vex-dialog-input input[type="date"]" [postcss-bem-linter]
1631:5	⚠  Invalid component selector ".vex.vex-theme-plain .vex-dialog-form .vex-dialog-input input[type="datetime"]" [postcss-bem-linter]
1632:5	⚠  Invalid component selector ".vex.vex-theme-plain .vex-dialog-form .vex-dialog-input input[type="datetime-local"]" [postcss-bem-linter]
1633:5	⚠  Invalid component selector ".vex.vex-theme-plain .vex-dialog-form .vex-dialog-input input[type="email"]" [postcss-bem-linter]
1634:5	⚠  Invalid component selector ".vex.vex-theme-plain .vex-dialog-form .vex-dialog-input input[type="month"]" [postcss-bem-linter]
1635:5	⚠  Invalid component selector ".vex.vex-theme-plain .vex-dialog-form .vex-dialog-input input[type="number"]" [postcss-bem-linter]
1636:5	⚠  Invalid component selector ".vex.vex-theme-plain .vex-dialog-form .vex-dialog-input input[type="password"]" [postcss-bem-linter]
1637:5	⚠  Invalid component selector ".vex.vex-theme-plain .vex-dialog-form .vex-dialog-input input[type="search"]" [postcss-bem-linter]
1638:5	⚠  Invalid component selector ".vex.vex-theme-plain .vex-dialog-form .vex-dialog-input input[type="tel"]" [postcss-bem-linter]
1639:5	⚠  Invalid component selector ".vex.vex-theme-plain .vex-dialog-form .vex-dialog-input input[type="text"]" [postcss-bem-linter]
1640:5	⚠  Invalid component selector ".vex.vex-theme-plain .vex-dialog-form .vex-dialog-input input[type="time"]" [postcss-bem-linter]
1641:5	⚠  Invalid component selector ".vex.vex-theme-plain .vex-dialog-form .vex-dialog-input input[type="url"]" [postcss-bem-linter]
1642:5	⚠  Invalid component selector ".vex.vex-theme-plain .vex-dialog-form .vex-dialog-input input[type="week"]" [postcss-bem-linter]
1653:7	⚠  Invalid component selector ".vex.vex-theme-plain .vex-dialog-form .vex-dialog-input textarea:focus" [postcss-bem-linter]
1654:7	⚠  Invalid component selector ".vex.vex-theme-plain .vex-dialog-form .vex-dialog-input input[type="date"]:focus" [postcss-bem-linter]
1655:7	⚠  Invalid component selector ".vex.vex-theme-plain .vex-dialog-form .vex-dialog-input input[type="datetime"]:focus" [postcss-bem-linter]
1656:7	⚠  Invalid component selector ".vex.vex-theme-plain .vex-dialog-form .vex-dialog-input input[type="datetime-local"]:focus" [postcss-bem-linter]
1657:7	⚠  Invalid component selector ".vex.vex-theme-plain .vex-dialog-form .vex-dialog-input input[type="email"]:focus" [postcss-bem-linter]
1658:7	⚠  Invalid component selector ".vex.vex-theme-plain .vex-dialog-form .vex-dialog-input input[type="month"]:focus" [postcss-bem-linter]
1659:7	⚠  Invalid component selector ".vex.vex-theme-plain .vex-dialog-form .vex-dialog-input input[type="number"]:focus" [postcss-bem-linter]
1660:7	⚠  Invalid component selector ".vex.vex-theme-plain .vex-dialog-form .vex-dialog-input input[type="password"]:focus" [postcss-bem-linter]
1661:7	⚠  Invalid component selector ".vex.vex-theme-plain .vex-dialog-form .vex-dialog-input input[type="search"]:focus" [postcss-bem-linter]
1662:7	⚠  Invalid component selector ".vex.vex-theme-plain .vex-dialog-form .vex-dialog-input input[type="tel"]:focus" [postcss-bem-linter]
1663:7	⚠  Invalid component selector ".vex.vex-theme-plain .vex-dialog-form .vex-dialog-input input[type="text"]:focus" [postcss-bem-linter]
1664:7	⚠  Invalid component selector ".vex.vex-theme-plain .vex-dialog-form .vex-dialog-input input[type="time"]:focus" [postcss-bem-linter]
1665:7	⚠  Invalid component selector ".vex.vex-theme-plain .vex-dialog-form .vex-dialog-input input[type="url"]:focus" [postcss-bem-linter]
1666:7	⚠  Invalid component selector ".vex.vex-theme-plain .vex-dialog-form .vex-dialog-input input[type="week"]:focus" [postcss-bem-linter]
```

If my understanding is correct, `postcss-bem-linter` only lints files that are `@define`'d, right? If not, why is my `ignoreSelectors` regex for `/\.vex.*/` not ignoring these?

Any help would be much appreciated!

**Comment by simonsmith** [comment] 2016-03-08 20:51
Maybe check the output of your Sass as that's what is going into postcss. It might be better to lint your components before they go through Sass.

**Comment by davidtheclark** [comment] 2016-03-08 21:36
Yeah, I'd suspect that your Sass compilation is concatenating all the files together, then as far as *this* plugin is concerned one `@define` comment might end up running over all kinds of files.

To lint components before they go through Sass, use postcss-scss.

**Comment by rfarine** [comment] 2016-03-08 21:37
@davidtheclark and @simonsmith Thank you! I'll try that out

**Comment by davidtheclark** [comment] 2016-03-08 21:39
OK. Since it's not a bug with the module but just the configuration of your build process, I'll close the issue.

**Closed by davidtheclark** 2016-03-08 21:39 UTC
