### ISSUE TITLE
support pattern interpolation

### ISSUE THREAD

**Issue by AndyOGo** [postcss/postcss-bem-linter#103] opened 2016-12-21 07:12 UTC
It would be really comfortable to be able to interpolate not only `{componentName}`, but also patterns like `{componentPattern}`.

Maybe a `patterns` options would make sense to allow for any custom pattern interpolations.

I mainly need this for readability and consistency.

**Example use case:** hyphenated BEM

**Comment by seamusleahy** [comment] 2017-02-22 06:35
I'm not sure what value these additional patterns would add to the rest of postcss-bem-linter. If the issue is solely about readability, you can use the native JavaScript string interpolation via [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals).

```javascript
const patternA = '-\w+';
const patternB = '-\d+';
//...
{
  componentSelectors: `^\\.{componentName}${patternA}${patternB}(?:-[a-zA-Z]+)?$`
};

```

**Comment by AndyOGo** [comment] 2017-02-22 07:30
@seamusleahy 
You are right it's solely about readability.

Agree, but this works only for `ES6`, if one specifies config as `JSON` this won't work.
Though this is what I ended up doing...

**Comment by simonsmith** [comment] 2017-07-02 14:40
Seems like using template literals is the way to go here. Closing

**Closed by simonsmith** 2017-07-02 14:40 UTC
